### ISSUE TITLE
[Write Access] Ellisisme 'Lemme try this again.'

### ISSUE THREAD

**Issue by ParadiseMCPE** [KadTheHunter/CityPlans#7] opened 2021-01-06 20:56 UTC
**EllisIsMe**, (of course) - **I don't have discord anymore and I'm probably not allowed to get it again**.

**Your projects have always interest me and I wanted to see what this newest one would be.**

Organization is key and considering my last messy "Write Access" was deleted, you seem to have everything quite organized. I'd love to contribute ideas and maybe eventually help construct stuff in the city (although at the moment I don't know how that would go.

**Comment by KadTheHunter** [comment] 2021-01-06 23:09
First of all, thank you for recreating your request using the proper form and data.

Your request to have access to contribute ideas and build in the City itself is being considered.

Now that we've handled the pleasantries, I'm going to abandon all pretext of professionalism, and just get the big question out of the way:

Why the hell should I (and those on my server who help me with the City such as Blue and Rex) trust you, given your history with me? To sum up just the events that **directly** involve you, should your memory fail you:

In Chronological Order:

- You were banned from the Original XOXO High RolePlay server for trying to get players to join **your** server
- You were in disgrace through much of 3.0 (though given your history with Cara, I think I'll voluntarily overlook this one)
- On the last incarnation of XOXO you were hardly online, abused your powers when you did, and then plotted to bring players to your server - or, rather, 'Chockys' server Paradise Network - which is what your current GitHub name is based off of, no? Then when your plan failed, you denied all knowledge of it, even though we had proof and witnesses.

As if those 3 key events weren't enough, there is also the numerous instances involving you, that either involved you indirectly, or involved you directly but you weren't the focus of the issue.

In addition to all *that*, there's also your ties (though this part I do assume) to the old community, including such people as Skull, Sunny, Unit, Nebula, Zer0, Noah, Dare, and the rest. After everything that's gone on with them, forget the more recent events with Becca, why should I let you in when you're still very much tied to them? I'm not saying you should leave friends to come here, I'm saying I wouldn't trust the others mentioned not to find a way here via you.

I suppose what I'm saying is, I'd like to trust you, and I'd like to invite you - indeed, welcome you - to KYT just like I would for any other player, but why should I, aforementioned reasons not to considered?

**Comment by ParadiseMCPE** [comment] 2021-01-07 00:43
I'd written a large-ass response but my junk computer died and deleted it so I'll simplify it. Your reasons for not trusting me make complete sense but I've been gone for 7+ months and have only spoken to Becca as well as Paige maybe twice during that time. I have zero loyalties at this point and have really no ties to the other servers. I'd also like to point out that Paige expressed after you left that I didn't ask her to join my server ever and only mentioned I was making one. You don't have to trust me and frankly it doesn't matter because I'm 90% sure my parents would never even allow me to help build the city anyway. I'm just here to contribute ideas take my word for it.

**Comment by KadTheHunter** [comment] 2021-01-07 01:24
> I'd written a large-ass response but my junk computer died and deleted it so I'll simplify it.
I sympathise completely (this isn't sarcasm, I'm completely serious because this happens with Reddit & My Phone often).

> Your reasons for not trusting me make complete sense but I've been gone for 7+ months and have only spoken to Becca as well as Paige maybe twice during that time.
I see.

> I have zero loyalties at this point and have really no ties to the other servers.
If this is true, it's a point in your favour. My only question about it, is what happened to Chocky and that mess?

> I'd also like to point out that Paige expressed after you left that I didn't ask her to join my server ever and only mentioned I was making one.
Well, well, well. Here I thought Paige was just a jackass because of Becca and Vens influence, and it turns out she's been a jackass since day one, and lied through her teeth to me about your situation. Sorry about the outcome.

> You don't have to trust me and frankly it doesn't matter because I'm 90% sure my parents would never even allow me to help build the city anyway. I'm just here to contribute ideas take my word for it.
Well ideas are still welcome, and your chances of having direct access to the city have increased quite a bit from several hours ago.
The only things holding me back, is the question mentioned above, and my prior resolve not to involve myself with *anyone*  from the past. I'll certainly consider your request, but given the concerns stated, and the fact the server is undergoing some massive changes in order to incorporate more features, you wouldn't get access immediately (or indeed for the next 2-4 weeks or so, knowing how things will likely go).

**Comment by ParadiseMCPE** [comment] 2021-01-07 01:43
Yeah that makes sense. 

Chocky cut me off instantly and really never spoke much to me other than technical stuff about the server. Only thing I miss are his builds in the end he was never a good friend. I reached out to him a 5-ish months ago apologizing about my absence but he's just as cut off from me as the rest of them.

I don't remember what exactly Paige expressed. but she basically said she'd twisted both Chocky's and my words and made it seem much more exaggerated. 

Becca did in fact tell me you were banned, poor choice of words using "left" sorry.

**Comment by KadTheHunter** [comment] 2021-01-07 02:04
> Chocky cut me off instantly and really never spoke much to me other than technical stuff about the server. Only thing I miss are his builds in the end he was never a good friend. I reached out to him a 5-ish months ago apologizing about my absence but he's just as cut off from me as the rest of them.

I got a flood of screenshots back when you were banned, of all sorts of conversations and things taking place. Didn't download them, but I remember it amounting to some sort of new division within your group, and Paradise being inactive. This was further confirmed by another ban later on (unrelated to yours until after the fact when they involved themselves with you). I believe you when you say you're cut off from them.


> I don't remember what exactly Paige expressed. but she basically said she'd twisted both Chocky's and my words and made it seem much more exaggerated.
> Becca did in fact tell me you were banned, poor choice of words using "left" sorry.

Ah ok, but the point still remains that she flat-out lied to me. Even saying she twisted the truth is stretching it in her favour. I remember most of the conversation related to your (now supposed) attempts to take players and leave, and she definitely put emphasis on the fact that you wanted to 'break away' and 'bring players'. Now I wonder just what else she lied to me about, and why. That, and what connection Becca had to it. I don't deny I used Becca sometimes for my own ends, but now I wonder if she used me equally. I'm not about to go asking anyone, but I'll definitely be thinking on it.


The server is currently whitelisted while I work on redoing portions of it (progress of which can be viewed [here](https://github.com/KadTheHunter/KYT-Reset-Planning/) )so I'm not giving the IP just yet, but once I reach my final decision (or the server is open, but final decision will likely come first), I'll post it here and tag you. Currently I don't really think you need access to commit into this repository, but you are welcome to comment on and open issues. In the future, if you have access to the City and are helping Build in it, I will give you commit access here.

**Comment by ParadiseMCPE** [comment] 2021-01-07 02:07
Sounds great thanks!

**Comment by ParadiseMCPE** [comment] 2021-01-07 02:09
Although I know you dislike Becca, I really don't think she was all that bad- you had your differences so obviously you both think each-other are the worst but I don't think she knew enough to have some secret master plan. Paige lied a ton but aside from the maybe-sneaky stuff about you getting banned I doubt she was conspiring against you... although you never know.

**Comment by KadTheHunter** [comment] 2021-01-07 02:16
> Although I know you dislike Becca, I really don't think she was all that bad- you had your differences so obviously you both think each-other are the worst but I don't think she knew enough to have some secret master plan. Paige lied a ton but aside from the maybe-sneaky stuff about you getting banned I doubt she was conspiring against you... although you never know.


The master plan comment is insanely on point, for a different reason/context. In the short post-ban argument, she insinuated that I had a 'master plan', and I should go follow it. 
*Ha, as if...*
This server didn't start until quite recently, and it's come on the heels of quite a few failures. Before this server I was mostly just wandering around or playing on a Prisons server.
She (Becca) was bad, and I was equally bad. Don't think there's much more to do with the whole thing besides alternate between thinking about it and ignoring it.

**Comment by KadTheHunter** [comment] 2021-01-10 19:23
@ParadiseMCPE 


I (as Owner of this Repository, as well as of MC Hangout Server [KYT]), have decided to grant you access to Build in the City.
The server is not currently open to the public (due to renovations and rewrites I've been doing this past week), but it will be reopened in a couple of days from now (anywhere from tonight, to Tuesday the 12th).


You will **not** be granted Write/Commit Access to this repository *immediately*, but it will be granted in the future once you have oriented yourself with the City and the Server.


Details for connecting to server and what to expect in-game (again, once it's unwitelisted!) are as follows:
IP: *mchangout.l*
Port: *25568*
Rank: *VIP*
To access the City, please enter the City Portal. You will automatically be given Creative Mode upon entering the City.
For further information on the server, use `/guide` and read the given Guidebook.


Thank you for requesting this access, congratulations on acceptance, and welcome to the City Build project, and MC Hangouts as a whole!


Sincerely,

~ Kaddicus

**Comment by ParadiseMCPE** [comment] 2021-01-12 20:18
Sorry should've seen this sooner but I was busy with school. Sounds good.

Thank you.

**Comment by KadTheHunter** [comment] 2021-01-12 20:21
@ParadiseMCPE 

Server is now un-whitelisted, but some documentation is missing in-game (Guidebook is outdated, Signage is missing, etc), and some features might not 100% work. The City and Plots should be working fine however.

> Details for connecting to server and what to expect in-game (again, once it's unwitelisted!) are as follows:
> IP: mchangout.l
> Port: 25568
> Rank: VIP
> To access the City, please enter the City Portal. You will automatically be given Creative Mode upon entering the City.
> For further information on the server, use /guide and read the given Guidebook.

**Comment by KadTheHunter** [comment] 2021-01-16 17:32
Closing as request is granted and resolved. For connection details please refer to the above comment.

**Closed by KadTheHunter** 2021-01-16 17:32 UTC
Labels: documentation, enhancement, question, solved
